### PR TITLE
Added Vue version check

### LINKED ISSUE #4: Add Vue version check
Add Vue version check to verify that this plugin supports it.

### PR DESCRIPTION
**Pull request by psmyrek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Internal: Added Vue version check. Closes #4.

### CODE REVIEW

**Review by pomek — APPROVED** [review]
LGTM. Would be good to cover this change by a unit test but I assume, it can be a challenge.

**Comment by psmyrek** [comment]
Yep, this will be difficult, because Vue in unit tests is loaded by the `@vue/test-utils` internally.

**Comment by psmyrek** [comment]
Code coverage dropped by 4.5% due to lack of test for this recently added Vue version check. No idea how to stub Vue version here... 🤔

**Comment by pomek** [comment]
As we have no idea how to stub the Vue version in tests, let's ignore this if while checking the code coverage.

**Pull request merged**
